#!/usr/bin/perl

# Modo de uso:
# $ls
# caca-01.avi
# [Wzf]caca 02.mpg
#
# $full_rename -n bosta
# bosta 01.avi
# bosta 02.mpg

$name = "Nueva Serie"; #Nuevo Nombre para los archivos

while (@ARGV && $ARGV[0] =~ m/^-/) {
   $_=shift(@ARGV);
   if (m/^-h$/ || m/^--help$/) {           # si el parametro es -h o --help
      print `echo 'Uso: rename -OPTION \nOptions:\n-h | --help: Imprime esta Ayuda\n-v | --version: Imprime la version del Programa\n-n | --name  <Nombre del Archivo>: selecciona el nombre por el cual renombrar'`;
      exit(1);
   } elsif (m/^-v$/ || m/^--version$/) {   # si el parametro es -v o --version
      print `echo 'rename. Version 0.5\nMade by Vendaval\nBased on edit_tracks.'`;
      exit(1);
   } elsif (m/^-n$/ || m/^--name$/) {      # si el parametro es -n o --name
      $_=shift(@ARGV);
      if(m/^-/){                           # si el parametro es -
         print `echo 'Uso incorrecto de -n o --name'`;
         exit(1);
      }elsif (m/..*/){
         $name = $_;
      }else{
         print `echo 'Uso incorrecto de -n o --name'`;
         exit(1);
      } # if
   } else {
      print `echo 'error inesperado'`;
      exit(1);
   } # if
} # while

$cero     = '0';
$contador = 01;                                      # contador de pista en la carpeta

opendir(DIR, ".");
@array = sort(grep(/.*\.(avi|mp4|mpeg|rmvb)/i,readdir(DIR))); # @array = sort(grep(/pl$/, readdir(DIR)));
closedir(DIR);

foreach (@array) {                                   # para todas las lineas del archivo leido

   if ( $_ ne "list\n" ){                            # si no es el archivo list ya borrado

      s/\n//;                                        # saco el "fin de linea" de la linea actual
      $comando = "mv \"$_\"";                        # agrego el comando 'mv', y entre comillas el nombre del archivo

      if (/(\.\w\w\w)$/){
         $extencion = $_ ;
         $extencion =~ s/.*(\.\w\w\w)$/$1/;
      }else{
         $extencion = "";
      } # if
      $comando = "$comando \"$name$extencion";       # agrego el nombre final del archivo y la comilla de apertura

      $aux = $_;
      $_   = $comando;                               # la variable actual pasa a ser el comando

      if (/(\.\w\w\w)$/){                            # si tiene extención

         if ($contador < 10) {                       # si el contador es menor que 10
            s/(\.\w\w\w)$/ $cero$1/;
            s/(\.\w\w\w)$/$contador$1/;
         }else{
            s/(\.\w\w\w)$/ $contador$1/;             # agrego contador antes del punto
         } # if

      }else{
         $_ = "$_ ";
         if ($contador < 10) {                       # si el contador es menor que 10
            $_ = "$_$cero";                          # entonces agrego un cero
         } # if
         $_ = "$_$contador";                         # agrego el contador y cierro las comillas
      } # if

      $_ = "$_\"";                                   # cierro las comillas

      print `$_`;                                    # ejecuto el comando

      $contador++;
      $_ = $aux;                                     # por las dudas restauro la variable

   } # if

} # while

print `ls`;
